### ISSUE TITLE
ansible-lint messages are cut off

### ISSUE THREAD

**Issue by hjudt** [jamescherti/flymake-ansible-lint.el#1]
Gave this a try, unfortunately, some messages are cut off, like:
`ansible-lint [yaml[truthy]]: Truthy value should be one of \[false, true]`

This is what ansible-language-server returns, but with flymake-ansible-lint flymake only writes:
`ansible-lint [yaml[truthy]]: Truthy value should be one of`

This is just one example.

**Comment by jamescherti** [comment]
Hello @hjudt,

This issue is a bug in `ansible-lint`, not in `flymake-ansible-lint`. To report this bug, please visit the following link: https://github.com/ansible/ansible-lint/issues

It is `ansible-lint` that cuts off error messages: 
```
$ ansible-lint -p test.yaml
WARNING  Listing 1 violation(s) that are fatal
test.yaml:5: yaml[truthy]: Truthy value should be one of
Read documentation for instructions on how to ignore specific rule violations.

             Rule Violation Summary
 count tag          profile rule associated tags
     1 yaml[truthy] basic   formatting, yaml

Failed after min profile: 1 failure(s), 0 warning(s) on 1 files.
```

In the future, I plan to make `flymake-ansible-lint` use `ansible-lint`'s JSON output. This change will allow parsing structures like:
```
$ ansible-lint test.yaml -f json
[{"type": "issue", "check_name": "yaml[truthy]", "categories": ["formatting", "yaml"], 
"url": "https://ansible-lint.readthedocs.io/rules/yaml/", "severity": "info", 
"level": "error", "description": "Truthy value should be one of \\[false, true]", 
"fingerprint": "******************************************", 
"location": {"path": "test.yaml", "lines": {"begin": 5}}}]
```

I'll have to refactor the code to do this. Contributions are welcome.
